version: '3.8'

services:
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
    container_name: db
  backend:
    build: ./example-backend  
    environment:
      - REDIS_HOST=redis 
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - VIRTUAL_HOST=http://127.0.0.1/
      #- VIRTUAL_HOST=backend.colasloth.com
    # Not needed as the service as EXPOSe in dokerfile
    #  - VIRTUAL_PORT=8080
    expose:
      - "8080"
    # networks:
    #   - app_network
    container_name: backend
    ports:
      - 8080
    # networks:
    #   - proxy
  redis:
    image: redis
    container_name: redis         
  frontend:
    build: ./example-frontend
    depends_on:
      - db
    container_name: frontend
    environment:
      - VIRTUAL_HOST=http://127.0.0.1
     # - VIRTUAL_HOST=frontend.colasloth.com
    #  - VIRTUAL_PORT=5000
    # networks:
    #   - app_network
    expose:
      - "5000"
    ports:
      - 5000
    networks:
      - proxy
  proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/certs
      - ./nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - 80:80    
      
    networks:
      - proxy
networks:
  proxy:
    name: proxy   
