version: '3.8'
services:
  db:
    image: postgres:13.2-alpine
    #restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
    #container_name: db_backend
    volumes:
      - database:/var/lib/postgres
  backend:
    build: ./example-backend
    environment:
     # - REDIS_HOST=redis 
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
   
    ports:
      - 8080:8080
  # redis:
  #   image: redis
  #   container_name: redis    
  frontend:
    build: ./example-frontend
    ports:
      - 5000:5000
volumes:
  database:
