version: '3.8'

services:
  backend:
    build: ./example-backend
    environment:
      - REDIS_HOST=redis 
    ports:
      - 8080:8080
  redis:
    image: redis
    container_name: redis    
  frontend:
    build: ./example-frontend
    ports:
      - 5000:5000
